### ISSUE TITLE
User Case: As an author, I want to attach a picture to my questions or my answers.

### ISSUE THREAD

**Issue by heykevin** [CMPUT301F14T02/Agora#11]

**Comment by djphan** [comment]
I'm Grabbing This One.

**Comment by djphan** [comment]
I realized that this is Part of PostAQuestion and PostAnAnswer Use Case. Image prompt is described here. Closing Issue.

**Comment by djphan** [comment]
Since this was unlinked from the other use cases. I am re opening this Use Case. As well I am taking it and writing the test cases.

**Comment by djphan** [comment]
Added TestCase JCase
