### ISSUE TITLE
Use Case: As a user I want to sort questions based on the presence of a photo, date, up votes, or favourites

### ISSUE THREAD

**Issue by jcairo** [CMPUT301F14T02/Agora#26]
This consolidate 2 user stories, original issues #13, and #19.

**Comment by jcairo** [comment]
Use cases for this story are complete.

**Comment by heykevin** [comment]
This is pretty much filter by photo/favourite. And I've already done picture so I'll do favourite as well.

**Comment by heykevin** [comment]
Actually I'll do test cases for whole thing.
