### ISSUE TITLE
Develop Basic Question/Answer View

### ISSUE THREAD

**Issue by djphan** [CMPUT301F14T02/Agora#30]

**Comment by djphan** [comment]
Changing the view from an Expandable List View to a basic List View. Adapters need to be made for the view. Changes need to be updated on Story Board. If time permits use expandable list view.

**Comment by sobolews** [comment]
The individual views appear to be complete.
I will link the MainActivity (Question View) to the AnswerActivity

**Comment by sobolews** [comment]
Functionality is complete, questions are viewable and clickable. Needs to look a bit nicer though.
