### ISSUE TITLE
AuthorQuestion View

### ISSUE THREAD

**Issue by djphan** [CMPUT301F14T02/Agora#35]

**Comment by djphan** [comment]
Kevin: Requires to fix the buttons.

**Comment by heykevin** [comment]
For future references once we have the controller hooked up. Should we have the author view switch to the newly posted question or back to the browse view?

**Comment by sobolews** [comment]
I think back to the browse view... what does everyone else think?

**Comment by djphan** [comment]
Browse view makes more sense.

**Comment by sobolews** [comment]
I'm going to go ahead and hook the controller up to this view now.

**Comment by sobolews** [comment]
Author Question View appears to be fully functional.
