### ISSUE TITLE
Feedback - Consider what happens when the app crashes mid connection/update/before the app can fully connect to the internet

### ISSUE THREAD

**Issue by djphan** [CMPUT301F14T02/Agora#48]

**Comment by sobolews** [comment]
I guess we don't need to deal with this. If we lose the connection, then the requests will be pushed to the webserver when we regain a connection, and if the app crashes in the meantime then we don't deal with it and the user's changes are lost. 

So the only thing to worry about is just implementing the queue of things to push in memory, but not serializing it. And even that can wait until Part 4.
