### ISSUE TITLE
Feedback - Change Sorting UI. Too Cluttered? 

### ISSUE THREAD

**Issue by djphan** [CMPUT301F14T02/Agora#49]

**Comment by djphan** [comment]
Implementing a Custom Dialogue Window to make menu larger.

**Comment by jaeyoon1** [comment]
Will be updating the storyboard to reflect this.

**Comment by djphan** [comment]
Dialoge Window Complete. Requires button functions to be hooked up to sorting. This will be implemented as part of Part 4.

**Comment by jaeyoon1** [comment]
storyboard updated to show a dialogue popup instead of a small dropdown.

**Comment by djphan** [comment]
Added scrolling function to the window when the user rotates the screen.

**Comment by djphan** [comment]
Consider adding this function as an extra: http://stackoverflow.com/questions/7557265/prevent-dialog-dismissal-on-screen-rotation-in-android
