### ISSUE TITLE
Use Case: As a user, I want to view a question and its answers.

### ISSUE THREAD

**Issue by heykevin** [CMPUT301F14T02/Agora#5]

**Comment by djphan** [comment]
I will grab this case preemptively before everyone does.

**Comment by djphan** [comment]
Added Use Case to Wiki

**Comment by djphan** [comment]
jCase Units should refer to add questions and add answers as we instantiate the models and use the .Get functions to return the question/answer.

**Comment by jcairo** [comment]
This is done and linked in the wiki
