### ISSUE TITLE
TA Feedback: Rearrange the Q and A view

### ISSUE THREAD

**Issue by djphan** [CMPUT301F14T02/Agora#50]
Change up the Question and Answer View to simplify it.

**Comment by jaeyoon1** [comment]
Since the question, answer and the comments will now have its own views,
how will the user access the comments from the question/answer view.

should each listview item have a "view comments" button or should it be accessed by something like longclicks.

**Comment by djphan** [comment]
i believe at the current version that we should have a view comments button and load in the comments in a separate activity.

**Comment by djphan** [comment]
As Carl said Victor only needs simple and using the same list view approach.

**Comment by djphan** [comment]
Fixed for project part 3
