### ISSUE TITLE
Write model tests for Question, Answer, Comments

### ISSUE THREAD

**Issue by heykevin** [CMPUT301F14T02/Agora#54]
Finished tests for question.

**Comment by heykevin** [comment]
Have a weird bug using Android jUnit tests where it says no tests found in the model.

**Comment by djphan** [comment]
Can you show us the code?

**Comment by heykevin** [comment]
It's in the repo already as QuesAnsComModelTest

**Comment by djphan** [comment]
Tagged as fixed since public void test<blah blah> was added. Are the tests all done? If so can you close this Kevin?
