### ISSUE TITLE
Searching for nested objects on the server doesn't work

### ISSUE THREAD

**Issue by jcairo** [CMPUT301F14T02/Agora#55]
Can't search answer bodies.

**Comment by djphan** [comment]
As in from the manager? Or from the app?

**Comment by sobolews** [comment]
What query are you currently trying to use?

**Comment by sobolews** [comment]
I think to search answers effectively, we need to be storing them as nested types. Is this being done?

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-nested-type.html

**Comment by sobolews** [comment]
We've found the solution to this.
Leaving the issue open though until we've implemented the code to parse through the returned documents to find the correct matching answers.
