### ISSUE TITLE
Views should be updated when they come back into view

### ISSUE THREAD

**Issue by sobolews** [CMPUT301F14T02/Agora#60]
For example, I'm in MainActivity, then I go to author a question, then I hit the back button. I think the MainActivity view should refresh itself when it comes back into view (by calling the controller to get an updated data set). 
Perhaps in the onResume method?

**Comment by djphan** [comment]
Based on this link we can either use onResume or onStart as we are switching activities. http://developer.android.com/training/basics/activity-lifecycle/pausing.html

**Comment by djphan** [comment]
Oh. I just read the next section. Onresume captures more cases and we'd want to use that. On Start captures the case when you leave the app (i.e. home button).

**Comment by sobolews** [comment]
This works for MainActivity, however only _sometimes_ after authoring a question, it appears immediately in MainActivity and sometimes not, probably because there's a race condition between the elasticsearch managing to index the new question vs the MainActivity requesting all Questions. 
I've added a manual refresh button (which just calls onResume directly) to the main activity action bar as a temporary fix.
