### ISSUE TITLE
Extra: Find an Optimal Way to Update Main Activity from Add Question Author View

### ISSUE THREAD

**Issue by djphan** [CMPUT301F14T02/Agora#62]
Use a flag and if true then set the 100ms delay?

**Comment by sobolews** [comment]
Did it!

```
        (new Handler()).postDelayed(new Runnable() {
            public void run() {
                refresh();
            }
        }, 2000);
```

inside onResume causes the activity to automatically refresh itself 2 seconds later, causing the new Question to magically appear! :dancers:
