### ISSUE TITLE
The flag icon: change it or keep it?

### ISSUE THREAD

**Issue by sobolews** [CMPUT301F14T02/Agora#85]
Can we all vote on whether to keep the flag icon?

Some people have noted that it looks like a "Flag as spam" or "Report user" kind of icon. Is there a better icon we could use for "Cached" instead?
Suggestions?

**Comment by heykevin** [comment]
Since it's analogous to saving, i think we should have some type of save icon.

**Comment by djphan** [comment]
I have a red tag used. I'll push a current version of it

**Comment by sobolews** [comment]
Looks good Dan
